#define CHORDAL_HOLD
#define ONESHOT_TAP_TOGGLE 2

#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "zame4/qmGKw3"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

